# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
ru:
  languageCode: ru-ru
  contentDir: content/ru
  title: Мой блог
  params:
    description: 
  menu:
    main:
    - name: "Обо мне"
      url: "#about"
      weight: 10
      identifier: "about"
    - name: "Блог"
      url: "#posts"
      weight: 20
      identifier: "posts"
    - name: "Проекты"
      url: "#projects"
      weight: 30
      identifier: "projects"
 #   - name: "Публикации"
 #     url: "#featured"
 #     weight: 40
      identifier: "featured"
    - name: "Курсы"
      url: "courses/"
      weight: 50
      identifier: "courses"
    - name: "Контакты"
      url: "#contact"
      weight: 60
      identifier: "contacts"
